#!/usr/bin/env sh

if csrutil status | grep -v disabled; then
    echo "SIP disabled, running --load-sa"
    yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
    # sudoers must have entry to allow yabai to run without a password here
    sudo yabai --load-sa
else
    echo "SIP enabled, skipping --load-sa"
fi

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                off            \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    window_opacity               off            \
    #active_window_opacity        1.0            \
    #normal_window_opacity        0.9            \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                on             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  00             \
    bottom_padding               00             \
    left_padding                 00             \
    right_padding                00             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

echo "Running"
