#!/usr/bin/env bash
set -euo pipefail

# Set to true for debugging and look for ~/yabai.<timestamp>.log
LOG=false

config=(
    mouse_follows_focus          off
    focus_follows_mouse          off
    window_origin_display        default
    window_placement             second_child
    window_zoom_persist          on
    window_topmost               off
    window_shadow                off
    window_animation_duration    0.0
    window_animation_frame_rate  120
    window_opacity_duration      0.1
    active_window_opacity        1.0
    window_opacity               on
    active_window_opacity        1.0
    normal_window_opacity        0.95
    active_window_border_color   0xff775759
    normal_window_border_color   0xff555555
    window_border_width          2
    window_border_radius         12
    window_border_blur           off
    window_border_hidpi          on
    window_border                on
    split_ratio                  0.50
    split_type                   auto
    auto_balance                 off
    top_padding                  00
    bottom_padding               00
    left_padding                 00
    right_padding                00
    window_gap                   06
    layout                       bsp
    mouse_modifier               fn
    mouse_action1                move
    mouse_action2                resize
    mouse_drop_action            swap
)

print_config() {
    # Print the config array in columns
    echo "config=("
    for ((i = 0; i < ${#config[@]}; i+=2)); do
        key="${config[i]}"
        value="${config[i+1]}"
        printf "%-10s %s\n" "$key" "$value"
    done | column -t | awk '{print "    " $0}'
    echo ")"
}

sa() {
    if csrutil status | grep -q disabled; then
        echo "SIP disabled, running --load-sa"
        set -x
        yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
        sudo yabai --load-sa
        set +x
    else
        echo "SIP enabled, skipping --load-sa"
    fi
}


run() {
    local command="yabai -m config"

    for ((i = 0; i < ${#config[@]}; i+=2)); do
        key="${config[i]}"
        value="${config[i+1]}"
        command+=" $key $value"
    done

    set -x
    $command
    set +x

    echo "Running"
}

log_name() {
    local timestamp="$(date +"%a%d-%b-%Y_%H:%M:%S")"
    echo "yabai.$timestamp.log"
}

main() {
    print_config
    sa
    run
}

logfile="$HOME/$(log_name)"

if [[ $LOG == true ]]; then
    main | tee -a "$logfile"
else
    main
fi

