#!/usr/bin/env bash
set -euo pipefail
HOME="${HOME:-/Users/matt}"  # Is $HOME available when run from launchd?

plist="$HOME/Library/Preferences/com.fujitsu.pfu.ScanSnapHomeSetting.plist"
if [[ ! -f "$plist" ]]; then
  exit 0
fi

destinations=("$HOME/.dotfiles/Library/Preferences" "$HOME/OneDrive/Backup/ScanSnap Settings")
for d in "${destinations[@]}"; do
  if [[ -d $d ]]; then
	cp -f "$plist" "$d/"
  fi
done

