endpoint: https://esentire.atlassian.net
user: matt.olenik
password-source: keyring
project: &project DEVOPS
custom-commands:
  #
  # new
  #
  - name: new
    help: Create issue helper
    options:
      - name: priority
        short: r
        type: ENUM
        default: P3
        enum: [P0, P1, P2, P3, P4]
        help: "Issue priority: P0 (emergency), P1 (urgent), P2 (important), P3 (normal), P4 (trivial). Defaults to p3"
      - name: project
        short: p
        default: *project
        help: "Project name, such as DEVOPS, HANTO, etc."
      - name: type
        short: t
        type: ENUM
        default: Story
        enum: [story, epic]
    args:
      - name: title
        required: true
      - name: description
        required: true
    script: |-
      {{jira}} create -p {{options.project}} -o "assignee={{options.user}}" -o "summary={{args.title}}" -o "description={{args.description}}" -o "priority={{options.priority}}" -i "{{options.type}}"

  #
  # mine
  #
  - name: mine
    help: display issues assigned to me
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list --template table --query "sprint in openSprints() and type != epic and resolution = unresolved and project=$JIRA_PROJECT ORDER BY rank asc, created"
      else
          # otherwise list issues for all project
          echo "\"project: ...\" configuration missing from .jira.d/config.yml"
      fi
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list --template table --query "resolution = unresolved and assignee=currentuser() and project = $JIRA_PROJECT ORDER BY priority asc, created"
      else
          # otherwise list issues for all project
          {{jira}} list --template table --query "resolution = unresolved and assignee=currentuser() ORDER BY priority asc, created"
      fi

  #
  # sprint
  #
  - name: sprint
    help: display issues for active sprint
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list --template table --query "sprint in openSprints() and type != epic and resolution = unresolved and project=$JIRA_PROJECT ORDER BY rank asc, created"
      else
          # otherwise list issues for all project
          echo "\"project: ...\" configuration missing from .jira.d/config.yml"
      fi
