#!/bin/sh
set -uo
DOTDIR="${DOTDIR:-"$PWD/.."}"
TMUX_PLUGIN_DIR="${TMUX_PLUGIN_DIR:-"$HOME/.tmux/plugins"}"

fail() { echo "$*" 1>&2; exit 1; }
command_exists() { command -v "$1" >/dev/null 2>&1; }
require() { if ! command_exists "$1"; then fail "$1 is required for rcm post-up"; fi }

require git

install_tpm() {
  tpm="$TMUX_PLUGIN_DIR/tpm"
  if [ ! -e "$tpm" ]; then
    git clone --depth 1 https://github.com/tmux-plugins/tpm "$tpm"
  fi
}

install_tmux_powerline() {
  tmux_powerline="$TMUX_PLUGIN_DIR/tmux-powerline"
  if [ ! -e "$tmux_powerline" ]; then
    git clone --depth 1 https://github.com/erikw/tmux-powerline "$tmux_powerline"
  fi
}

restore_scansnap_plist() {
  require rsync
  plist="Library/Preferences/com.fujitsu.pfu.ScanSnapHomeSetting.plist"
  rsync -u "$DOTDIR/$plist" "$HOME/$plist"
}

setup_all() {
  install_tpm
  install_tmux_powerline
}

setup_macos() {
  restore_scansnap_plist
}

setup_all
if [ "$(uname)" = "Darwin" ]; then
  setup_macos
fi

