#!/bin/sh

PLUG="$HOME/.local/share/nvim/site/autoload/plug.vim"
TMUX_PLUGIN="$HOME/.tmux/plugins"
TPM="$TMUX_PLUGIN/tpm"
TMUX_POWERLINE="$TMUX_PLUGIN/tmux-powerline"

if [ ! -e "$PLUG" ]; then
  curl -fLo "$PLUG" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ ! -e "$TPM" ]; then
  git clone https://github.com/tmux-plugins/tpm "$TPM"
fi

if [ ! -e "$TMUX_POWERLINE" ]; then
  git clone https://github.com/erikw/tmux-powerline "$TMUX_POWERLINE"
fi
