#!/bin/sh

PLUG_PATH="$HOME/.local/share/nvim/site/autoload/plug.vim"
TPM_PATH="$HOME/.tmux/plugins/tpm"

if [ ! -e "$PLUG_PATH" ]; then
  curl -fLo "$PLUG_PATH" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ ! -e "$TPM_PATH" ]; then
  git clone https://github.com/tmux-plugins/tpm "$TPM_PATH"
fi
