#!/usr/bin/env zsh

alias livecat='watch --color -n 1 ccat --color=always'
alias edit-zshrc="$EDITOR ~/.zshrc"
alias source-zshrc='source ~/.zshrc'
alias edit-tmuxconf="$EDITOR ~/.tmux.conf"
alias http-get='curl -w "\n%{http_code}"'
alias http-post='curl -w "\n%{http_code}" -X POST'
alias http-put='curl -w "\n%{http_code}" -X PUT'
alias http-delete='curl -w "\n%{http_code}" -X DELETE'
alias http-head='curl -w "\n%{http_code}" -I'
alias http-get-status='curl -s -o /dev/null -w "%{http_code}"'
alias gitroot='git rev-parse --show-toplevel'
alias rg='rg --smart-case'

mkcd() { mkdir -p $1 && cd $1 }
pidof() { ps aux | grep -i "$1" | awk '{print $2}' }
mypidof() { ps ux | grep -i "$1" | awk '{print $2}' }
psinfo() { ps aux | grep -i "$1" }
mypsinfo() { ps ux | grep -i "$1" }
spy() { fswatch -0 -o "$1" | xargs -0 -n 1 -I {} ${@[2, -1]} }

command_exists mdfind && alias mdhere='mdfind -onlyin .'
command_exists go && export GOPATH="$HOME/go" && export PATH="$GOPATH/bin:$PATH"
