#!/usr/bin/env bash
fail()        { echo "$1" 1>&2; exit "${2:-1}"; }
fail_if()     { eval "$1" && fail "$2" "${3:-1}"; }
fail_unless() { eval "$1" || fail "$2" "${3:-1}"; }

# Usage
#   fail_if $'<bash shell expression>' "Failure description" [exitCode]
# Example
#   # This exits with 0:
#   fail_unless $'[[ $(uname) == Darwin ]]' "This program is only supported on macOS"
#   # This exits with 5:
#   fail_if $'[[ $(uname) == Darwin ]]' "This program is NOT supported on macOS" 5

